#!/usr/bin/env groovy

def projectDir = '/var/jenkins_home/master/play-a'

pipeline {
    agent any
    options {
        skipDefaultCheckout true
    }
    stages {
        stage('init') {
            steps {
                echo "começo de build do play a"

                }
            }
        }
    }
}
