#!/usr/bin/env groovy

def projectDir = '/var/lib/jenkins/master/monorepo-library'

pipeline {
    agent any
    options {
        skipDefaultCheckout true
    }
    stages {
        stage('init') {
            steps {
                echo "começo de build do monorepo-library"

                }
            }
        }
    }
}

